trigger:
  branches:
    include: 
    - refs/heads/master 
  batch: True

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'src/Bubble.Library.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(projectName)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: $(projectName)

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: $(projectName)
    nobuild: true
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: 'push $(Build.ArtifactStagingDirectory)/**/*.nupkg -s https://api.nuget.org/v3/index.json -k $(APIKey) -n --skip-duplicate'