trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectCsproj: 'Bubble.Library.csproj'

steps:
- checkout: self
  clean: true
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(projectCsproj)
    restoreArguments: ' -s http://nuget.ehi.com.cn/v3/index.json'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: $(projectCsproj)
    versioningScheme: byBuildNumber
    packDirectory: $(Build.ArtifactStagingDirectory)
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: 'push $(Build.ArtifactStagingDirectory)/*.nupkg -s https://api.nuget.org/v3/index.json -k $(APIKey)'